steps:
  # 1. Build de l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/front-dev', '-f', 'frontend/Dockerfile', 'frontend/']

  # 2. Push de l'image vers le registre
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/front-dev']

  # 3. Déploiement sur Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mon-app-front-dev'
      - '--image'
      - 'gcr.io/$PROJECT_ID/front-dev'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

# CETTE PARTIE RÉGLE TON PROBLÈME DE LOGS
options:
  logging: CLOUD_LOGGING_ONLY