

services:
  # La Base de Données (postgres:15 Debian pour compatibilité Mac ARM)
  database:
    image: postgres:15
    platform: linux/arm64
    container_name: cda-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  # Le Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cda-back
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}?schema=public
    depends_on:
      - database

  # Le Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cda-front
    restart: always
    ports:
      - "3000:8080"
    depends_on:
      - backend

volumes:
  db-data:
