steps:
  # 1. Build de l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mon-backend-image', '.']

  # 2. Push de l'image sur Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mon-backend-image']

  # 3. Déploiement sur Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cda-back'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mon-backend-image'
      - '--region'
      - 'europe-west9'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      # C'est cette ligne qui permet à Prisma de "voir" la base de données :
      - '--set-cloudsql-instances'
      - 'project-f676239d-0023-40fd-a9c:europe-west9:cc-bdd'
      - '--update-env-vars'- 'DATABASE_URL=DATABASE_URL:latest'

images:
  - 'gcr.io/$PROJECT_ID/mon-backend-image'